web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./content:/content
        - ./site.conf:/etc/nginx/conf.d/default.conf

    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./content:/content
